# Numpay Working with Matrics in Python

## Import the Required Package

In [3]:
import numpy as np

## Create The Array

In [5]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)  # [1 2 3 4 5]

[1 2 3 4 5]


## Create The Indexing use Array

In [7]:
arr = np.array([1, 2, 3, 4, 5])

# Indexing
print(arr[0])  # 1
print(arr[-1])  # 5

1
5


## Create The Slicing

In [9]:
print(arr[1:3])  # [2 3]
print(arr[:3])  # [1 2 3]
print(arr[2:])  # [3 4 5]

[2 3]
[1 2 3]
[3 4 5]


## Apply The Addition and Multiply

In [11]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [12]:
print(arr1 + arr2)  # [5 7 9]
print(arr1 * arr2)  # [ 4 10 18]

[5 7 9]
[ 4 10 18]


In [13]:
print(np.add(arr1, arr2))  # [5 7 9]
print(np.multiply(arr1, arr2))  # [ 4 10 18]

[5 7 9]
[ 4 10 18]


## Apply The Matrics

In [15]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(np.dot(arr1, arr2))  # [[19 22], [43 50]]

[[19 22]
 [43 50]]


## Use The Mean, Median, Mode, Standard Deviation

In [17]:
arr = np.array([1, 2, 3, 4, 5])
print(np.mean(arr))  # 3.0
print(np.median(arr))  # 3.0
print(np.std(arr))  # 1.4142135623730951

3.0
3.0
1.4142135623730951


## Reshape The Array

In [19]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [20]:
print(np.reshape(arr, (2, 3))) 

[[1 2 3]
 [4 5 6]]


## Use Transpose

In [22]:
arr = np.array([[1, 2], [3, 4]])

In [23]:
print(np.transpose(arr))

[[1 3]
 [2 4]]


## Use Concatenate

In [25]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [26]:
print(np.concatenate((arr1, arr2)))

[1 2 3 4 5 6]


## Use The Spliting

In [28]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(np.split(arr, 2)) 

[array([1, 2, 3]), array([4, 5, 6])]
